
# Gem::Specification for Git-blog-2
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: git-blog
version: !ruby/object:Gem::Version 
  version: "2"
platform: ruby
authors: 
- elliottcable
autorequire: 
bindir: bin

date: 2008-06-26 00:00:00 -08:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: git
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: haml
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: simple, uber-minimalistic blogging software, that uses git as a storage system for posts, and deploys to your webserver with git as well. no dynamic content, by design.
email: 
- git-blog@elliottcable.com
executables: 
- git-blog
extensions: []

extra_rdoc_files: 
- bin/git-blog
- lib/git-blog/core_ext/file.rb
- lib/git-blog/core_ext/string.rb
- lib/git-blog/core_ext/symbol.rb
- lib/git-blog/core_ext.rb
- lib/git-blog/parser/haml.rb
- lib/git-blog/parser/html.rb
- lib/git-blog/parser/markdown.rb
- lib/git-blog/parser/textile.rb
- lib/git-blog/parsers.rb
- lib/git-blog/post.rb
- lib/git-blog.rb
- lib/git-blog.task
files: 
- bin/git-blog
- git-blog.gemspec
- lib/git-blog/core_ext/file.rb
- lib/git-blog/core_ext/string.rb
- lib/git-blog/core_ext/symbol.rb
- lib/git-blog/core_ext.rb
- lib/git-blog/parser/haml.rb
- lib/git-blog/parser/html.rb
- lib/git-blog/parser/markdown.rb
- lib/git-blog/parser/textile.rb
- lib/git-blog/parsers.rb
- lib/git-blog/post.rb
- lib/git-blog.rb
- lib/git-blog.task
- Rakefile
- task/echoe.task
- template/design/index.haml
- template/design/main.css
- template/design/post.haml
- template/post-receive.hook
- template/posts/welcome_to_your_git_blog.markdown
- .manifest
has_rdoc: false
homepage: http://find.elliottcable.name/git-blog
post_install_message: " - Thanks for installing git-blog!\n - To get started, run the following in the local directory\n - in which you want your new blog to reside:\n -   git blog init"
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Git-blog
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: git-blog
rubygems_version: 1.2.0
specification_version: 2
summary: Minimalistic, git based blogware
test_files: []
